name: Build Android Project

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      ANDROID_NDK: ${{ github.workspace }}/android-ndk-r25b
      NDK_PATH: ${{ github.workspace }}/android-ndk-r25b

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Android NDK
        run: |
          wget https://dl.google.com/android/repository/android-ndk-r25b-linux.zip
          unzip android-ndk-r25b-linux.zip -d $HOME
          mv $HOME/android-ndk-r25b $ANDROID_NDK
          echo "ANDROID_NDK=${ANDROID_NDK}" >> $GITHUB_ENV

      - name: Clean
        run: sudo ./clean.sh

      - name: Build for arm64
        run: sudo docker run --rm -v $(pwd):/python3-android -v ${NDK_PATH}:/android-ndk:ro --env ARCH=arm64 --env ANDROID_API=23 python:3.11.0-slim /python3-android/docker-build.sh --enable-shared --without-ensurepip --disable-ipv6 --with-build-python

      - name: Upload arm64 artifacts
        uses: actions/upload-artifact@v4
        with:
          name: arm64-build
          path: ./build/*

      - name: Clean
        run: sudo ./clean.sh

      - name: Build for arm
        run: sudo docker run --rm -v $(pwd):/python3-android -v ${NDK_PATH}:/android-ndk:ro --env ARCH=arm --env ANDROID_API=23 python:3.11.0-slim /python3-android/docker-build.sh --enable-shared --without-ensurepip --disable-ipv6 --with-build-python

      - name: Upload arm artifacts
        uses: actions/upload-artifact@v4
        with:
          name: arm-build
          path: ./build/*

      - name: Clean
        run: sudo ./clean.sh

      - name: Build for x86_64
        run: sudo docker run --rm -v $(pwd):/python3-android -v ${NDK_PATH}:/android-ndk:ro --env ARCH=x86_64 --env ANDROID_API=23 python:3.11.0-slim /python3-android/docker-build.sh --enable-shared --without-ensurepip --disable-ipv6 --with-build-python

      - name: Upload x86_64 artifacts
        uses: actions/upload-artifact@v4
        with:
          name: x86_64-build
          path: ./build/*
          
